config/routes.rb
Blog::Application.routes.draw do
  

  get 'admin' => 'admin#index'

  controller :sessions do 
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "admin/index"

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  root :to => 'Posts#index'
  resources :posts
  resources :users
  

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :title
  validates :title,  presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :password, :password_confirmation
  has_secure_password
  validates :name, presence: true, uniqueness: true
  validates :password, presence: true
  validates :password_confirmation, presence: true
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :authorize
  protect_from_forgery


  protected

    def authorize
      unless User.find_by_id(session[:user_id])
        redirect_to login_url, notice: 'Please Log In'
      end
    end
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_filter :authorize

  def index
    @post = Post.new
    @posts = Post.all 
  end

  def create
    @post = Post.create params[:post]
    if @post.save
      redirect_to posts_path, notice: 'Post was successfully created'
    else 
      redirect_to :back, notice: 'There was an error creating your post'
    end
  end

  def show
    @post = Post.find params[:id]
  end

  def edit
    @post = Post.find params[:id]
  end

  def update
    post = Post.find params[:id]

    if post.update_attributes params[:post]
      redirect_to posts_path, :notice => 'Your post was successfully updated.'
    else
      redirect_to :back, :notice => 'Cannot have an empty post.'
    end
  end

  def destroy
    Post.destroy params[:id]
    redirect_to :back, :notice => 'Post was successfully deleted'
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :authorize

  def new
  end

  def create
    user = User.find_by_name(params[:name])
    if user and user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to posts_url
    else redirect_to login_url, notice: "Invalid User/Password combination"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to posts_url, notice: 'Logged Out'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all

  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(params[:user])
    if @user.save 
      redirect_to users_url, notice: "User #{@user.name} was successfully created"
    else
      render  action: "new"
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to users_url, notice: "User #{@user.name} was successfully updated"
    else
      render action: "edit"
    end
  end

  def destroy
    User.destroy params[:id]
    redirect_to :back, :notice => 'User was successfully deleted'
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Admin#index</h1>
<p>Find me in app/views/admin/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |name, message| %>
  <%= content_tag :div, message, :id => "flash_#{name}" %>
  <% end %>

  <div class="header">
    <h1 class="title">Isaac's Blog</h1>
  </div>


  
  

    <%= yield %>

  </body>
  </html>

app/views/posts/_form.html.erb
<%= form_for @post do |p| %>
<div class="field">
  <%= p.label :title %><br/>
  <%= p.text_field :title %><br/>
  <%= p.label :body %><br/>
  <%= p.text_area :body, rows: 10, cols: 'auto' %><br/>
  <%= p.submit %>
</div>
  <% end %>

app/views/posts/edit.html.erb
<h1>Edit</h1>
<%= render 'form' %>

app/views/posts/index.html.erb
<div class="post_list">
  <% for post in @posts %>
    <p class="change" id="post_<%= post.id %>"><span class="post_link"><%= link_to "#{post.title}", post %></span><br/>
    <% if session[:user_id] %>
      <%= link_to 'Edit', edit_post_path(post) %>
      | <%= link_to 'Delete', post, :method => 'delete',:confirm => 'Are you sure you want to delete this post?'%></p>
    <% end %>
  <% end %>
</div>

  <div class="sidebar">
    <% if session[:user_id] %>
      <h3>Create a post:</h3>
      <%= render 'form' %>

      <%= link_to 'Logout', logout_path, method: :delete, confirm: 'Are you sure you want to log out?' %> <br/>
      <%= link_to 'Edit Users', users_path %>

      <% else %>
      <br/>
      <%= link_to 'Login', login_path %>
    <% end %>
  </div>

app/views/posts/show.html.erb
<h1>Showing Post</h1>
<h2> <%= @post.title %></h2>
<p><%= @post.body %></p>
<%= link_to 'Back to Posts', posts_path %>

app/views/users/_form.html.erb
<div class="field">

<%= form_for @user do |f|%>
  <% if @user.errors.any? %>
    <div>
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
  <legend>Enter User Details:</legend>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name, size: 40 %>
  </div>

  <div>
    <%= f.label :password, 'Password' %>
    <%= f.password_field :password, size: 40 %>
  </div>

  <div>
    <%= f.label :password_confirmation, 'Confirm Password' %>
    <%= f.password_field :password_confirmation, size: 40 %>
  </div>

  <div>
    <%= f.submit %>
  </div>
  </fieldset>
<% end %>

app/views/users/edit.html.erb
<h1>Edit</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<!--<% if notice %>
  <p id="flash_notice"><%= notice %></p>
  <% end %>!-->
  <div class="sidebar">
    <%= link_to 'Logout', logout_path, method: :delete, confirm: 'Are you sure you want to log out?' %> <br/>
    <%= link_to 'Back to Posts', root_path %>
  </div>
  <div class="post_list">

    <h1>Listing Users</h1>
    <table>
      <tr>
        <th>Name</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
      <% @users.each do |user| %>
      <tr>
        <td id="user_<% user.id %>"><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure you want to delete this user?'} %></td>
      </tr>
      <% end %>
    </table>
    <br/>

    <%= link_to 'Add new User', new_user_path %>
  </div>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= render 'form' %>
<br/>
<%= link_to 'Back to users', :back %>

app/views/users/show.html.erb
<h1>About this user</h1>
<h3>User Name:</h3>
<%= @user.name %>

<h3>Password:</h3>
<%= @user.password %>